export const GET_DEFAULT_HEADER_IMAGE = 'GET_DEFAULT_HEADER_IMAGE';

export const SET_FOLDER_HEADER = 'SET_FOLDER_HEADER';

export const SET_FOLDER_TABS = 'SET_FOLDER_TABS';

export const GET_PARENT_FOLDER_DATA = 'GET_PARENT_FOLDER_DATA';
